layout_spectrum: 0.3835126
typography_spectrum: 0.7777778
color:
  saturation: 0.1395213
  brandStrength: 0.09611169
  lightness: 0.1505376
  rhythmicContrast: 0.5127498
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: St. Josephs Church Bronxville
